# site settings
title: Welcome!
subtitle: (page currently in construction)
email: jorge@email.com
description: Personal website/portfolio.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog // THIS MIGHT BE MESSING UP STUFF
url: "https://js-acevedo.github.io" # the base hostname & protocol for your site
author:
street_address: 1234 Street St
city: Toronto
state: Ontario
zip_code: M5R 1R1
country: Canada
phone: (416) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/js-acevedo
  LinkedIn: https://www.linkedin.com/in/js.acevedo


# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- README.md